shared:
    image: node:8

parameters:
    region: "us-west-1"
    az:
        value: "1"
        description: "default availability zone"
    cluster: ["cluster1", "cluster2"]

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - step1: 'echo "Region: $(meta get parameters.region.value)"'
            - step2: 'echo "AZ: $(meta get parameters.az.value)"'
            - step3: 'echo "Cluster: $(meta get parameters.cluster.value)"'
            - step4: |
                RESULT=$(meta get parameters.cluster.value)
                echo $RESULT
