#shared:
#    image: node:6
#jobs:
#    # the main job is run in pull requests as well
#    main:
#        steps: 
#            - install: npm install screwdriver-template-main
#            - validate: ./node_modules/.bin/template-validate
#            - publish: ./node_modules/.bin/template-publish
#    tag:
#        steps:
#            - install: npm install screwdriver-template-main
#            - token: echo $SD_TOKEN
#            - tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag latest
#    use-tag:
#        template: tifftemplate@latest
---
shared:
    image: node:20
    steps:
        - echo: echo hi
jobs:
    a:
        requires: [~commit, ~pr]
    b:
        requires: [a, c]
    c:
        requires: [~commit, ~pr]
