shared:
  image: node:12
  steps:
    - echo: |
        echo "$COLO"
        echo "$BCP"
  environment:
    COLO: "bf2"
    BCP: "gq2"
jobs:
  main:
    requires: [~pr, ~commit]

  main2:
    requires: [main]
    environment:
      BCP: ${COLO}
  main3:
    requires: [~pr, ~commit]
    environment:
      COLO2: ${BCP}
    steps:
      - echo: |
          echo "$COLO"
          echo "$BCP"
