#shared:
#    image: node:6
#jobs:
#    # the main job is run in pull requests as well
#    main:
#        steps: 
#            - install: npm install screwdriver-template-main
#            - validate: ./node_modules/.bin/template-validate
#            - publish: ./node_modules/.bin/template-publish
#    tag:
#        steps:
#            - install: npm install screwdriver-template-main
#            - token: echo $SD_TOKEN
#            - tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag latest
#    use-tag:
#        template: tifftemplate@latest
---
version: 4
jobs:
    main:
        requires: [~pr, ~commit]
        sourcePaths: ['README.md']
        image: node:8
        steps:
            #- set: meta set build_version_1 1234567
            #- get: meta get build_version_1
            #- sleep: sleep 1500
            - echo2: echo meowmeow
            - meta: meta get $SOMERANDOMVAR
            - echo: meta set example.coverage 99.95
            #- publish: npx semantic-release
            #- install: npm install screwdriver-template-main
            #- tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag meow
