jobs:
    main:
        description: 'hello I am the first job that will run'
        requires: [~pr, ~commit]
        image: node:8
        steps:
            - echo: |
                cat $SD_SOURCE_DIR/ascii-art.txt
            - meta: |
                meta set meta.status.coverage '{"status":"SUCCESS","message":"Coverage is above 80%."}'
                meta set meta.status.lowercase2 '{"status":"success","message":"Coverage is above 80%."}'
                meta set meta.status.pendingTest '{"status":"PENDING","message":"Still working on it."}'
                meta set meta.status.lowercase3 '{"status":"pending","message":"Still working on it."}'
    
