#pipeline 8
jobs:
    external_fork:
        description: 'this is the production deploy job but really it just gets the external meta'
        requires: [~sd@6:main]
        image: node:8
        steps:
            - echo: echo hi
