shared:
    image: node:8
    steps:
        - echo: echo meow
jobs:
    trigger_periodically:
        requires: []
    trigger_staging:
        requires: [trigger_periodically]
    set_branch:
        requires: [trigger_staging]
