shared:
    image: node:8
    steps:
        - echo: echo wooff
jobs:
    stg-build-trigger:
        requires: [~sd@41:set_branch]
    stg-etl-primary:
        requires: [stg-build-trigger]
    stg-fe-bcp:
        requires: [stg-build-trigger]
    stg-fe-primary:
        requires: [stg-build-trigger]
    stg-deploy-trigger:
        requires: [stg-fe-primary, stg-fe-bcp, stg-etl-primary]
    prod-build-trigger:
        requires: [~sd@43:promote_stg_primary]
    prod-fe-primary:
        requires: [prod-build-trigger]
    prod-fe-bcp:
        requires: [prod-build-trigger]
    prod-etl-primary:
        requires: [prod-build-trigger]
    prod-etl-bcp:
        requires: [prod-build-trigger]
