jobs:
    main:
        annotations:
            screwdriver.cd/buildPeriodically: '* * * * *'
        description: 'hello I am the first job that will run'
        requires: [~pr, ~commit]
        image: node:8
        steps:
            - echo: |
                cat $SD_SOURCE_DIR/ascii-art.txt
            - cat: cp -a /sd/meta/. $SD_ARTIFACTS_DIR/meta/
    
