#shared:
#    image: node:6
#jobs:
#    # the main job is run in pull requests as well
#    main:
#        steps: 
#            - install: npm install screwdriver-template-main
#            - validate: ./node_modules/.bin/template-validate
#            - publish: ./node_modules/.bin/template-publish
#    tag:
#        steps:
#            - install: npm install screwdriver-template-main
#            - token: echo $SD_TOKEN
#            - tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag latest
#    use-tag:
#        template: tifftemplate@latest
---
jobs:
    main:
        description: 'hello I am the first job that will run'
        requires: [~pr, ~commit]
        image: node:8
        steps:
            - echo: |
                cat $SD_SOURCE_DIR/ascii-art.txt
    internal_fork:
        description: 'this is the production deploy job but really it just gets the external meta'
        requires: [main]
        image: node:8
        steps:
            - echo: echo hi
            - sleep: sleep 1m
    join_job:
        description: 'job to test the specific branch requires feature'
        requires: ['internal_fork', 'sd@2:external_fork', 'sd@4:external_fork']
        image: node:8
        steps:
            - echo: echo hi
