#shared:
#    image: node:6
#jobs:
#    # the main job is run in pull requests as well
#    main:
#        steps: 
#            - install: npm install screwdriver-template-main
#            - validate: ./node_modules/.bin/template-validate
#            - publish: ./node_modules/.bin/template-publish
#    tag:
#        steps:
#            - install: npm install screwdriver-template-main
#            - token: echo $SD_TOKEN
#            - tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag latest
#    use-tag:
#        template: tifftemplate@latest
---
jobs:
    main:
        description: 'hello I am the first job that will run test some things'
        requires: [~pr, ~commit]
        image: node:8
        steps:
            - echo: |
                cat $SD_SOURCE_DIR/ascii-art.txt
            - meta: |
                meta set meta.status.findbugs '{"status":"FAILURE","url":"http://findbugs.com"}'
                meta set meta.status.lowercase1 '{"status":"failure","url":"http://findbugs.com"}'
                meta set meta.status.coverage '{"status":"PENDING"}'
                meta set meta.status.lowercase2 '{"status":"pending"}'
            - sleep: sleep 1m
            - cat: cp -a /sd/meta/. $SD_ARTIFACTS_DIR/meta/
    internal_fork1:
        description: 'this is the production deploy job but really it just gets the external meta'
        requires: [main]
        image: node:8
        steps:
            - echo: meta set meta.package.version "3206-internal"
            - overwrite: meta set sd.3983.external_fork1 ""
            - cat: cp -a /sd/meta/. $SD_ARTIFACTS_DIR/meta/
            - sleep: sleep 1m
    internal_fork2:
        description: 'this is the production deploy job but really it just gets the external meta'
        requires: [main]
        image: node:8
        steps:
            - echo: echo hi
            - cat: cp -a /sd/meta/. $SD_ARTIFACTS_DIR/meta/
    join_job:
        description: 'job to test the specific branch requires feature'
        requires: ['internal_fork1', 'internal_fork2', 'sd@3983:external_fork1', 'sd@3983:external_fork2']
        image: node:8
        steps:
            - echo: meta get meta.package.version
            #- echoExternal: meta get meta.package.version --external sd@3983:external_fork1
            - cat: cp -a /sd/meta/. $SD_ARTIFACTS_DIR/meta/
    join_downstream:
        requires: ['join_job']
        image: node:8
        steps:
            - echoExternal: meta get meta.package.version --external sd@3983:external_fork1
            - cat: cp -a /sd/meta/. $SD_ARTIFACTS_DIR/meta/
    
