shared:
  image: node:12
  steps:
    - echo: |
        echo "$COLO"
        echo "$BCP"
  environment:
    BCP: "gq2"
    COLO: "bf2"
jobs:
  main:
    requires: [~pr, ~commit]
  main2:
    requires: [main]
    environment:
      COLO: ${BCP}
  main3:
    requires: [~pr, ~commit]
    environment:
      BCP: ${COLO}
      BCP2: ${COLO}
    steps:
      - echo: |
          echo "$BCP"
          echo "$BCP2"
          echo "$COLO"
