#shared:
#    image: node:6
#jobs:
#    # the main job is run in pull requests as well
#    main:
#        steps: 
#            - install: npm install screwdriver-template-main
#            - validate: ./node_modules/.bin/template-validate
#            - publish: ./node_modules/.bin/template-publish
#    tag:
#        steps:
#            - install: npm install screwdriver-template-main
#            - token: echo $SD_TOKEN
#            - tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag latest
#    use-tag:
#        template: tifftemplate@latest
---
jobs:
    main:
        requires: [~pr, ~commit]
        image: node:8
        steps:
            #- set: meta set build_version_1 1234567
            #- get: meta get build_version_1
            #- sleep: sleep 1500
            - meta1: |
                NPM_PKG_VERSION=meow
                meta set docker_tag "v$NPM_PKG_VERSION"
                echo `meta get docker_tag`
            - write5: echo "meow" > $SD_ARTIFACTS_DIR/zzz.txt
            - meta: meta get $SOMERANDOMVAR
            - echo: meta set example.coverage 99.95
            #- publish: npx semantic-release
            #- install: npm install screwdriver-template-main
            #- tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag meow
    other_job:
        requires: [main]
        image: node:8
        steps:
            - hi: echo hi
            - meta: meta get example
