parameters:
  param:
    value: "foo"
  user:
      value: adong
      description: User running build

shared:
  image: node:14
    
jobs:
  main:
    requires: [ ~commit, ~pr ]
    steps:
      - show: |
          echo meta get parameters.param.value
      - show2: |
          echo meta get parameters.param
      - p2:  echo $(meta get parameters.user)
