shared:
  image: node:12
  steps:
    - echo: echo hi
jobs:
  A:
    requires: [~commit]
    steps:
      - set: meta set foo 50876e6
      - get: meta get foo
  B:
    requires: [~commit]
  C:
     requires: [A, B]
