shared:
    image: node:12

subscribe:
    scmUrls:
        - git@github.com:tkyi/quickstart-ruby.git#main: ['~commit']

jobs:
    main:
        annotations:
            screwdriver.cd/displayName: "display name"
        requires: [~pr, ~commit, ~subscribe]
        steps:
            - buildToken: echo ${SD_TOKEN}
            - sleep: sleep 5m
