#shared:
#    image: node:6
#jobs:
#    # the main job is run in pull requests as well
#    main:
#        steps: 
#            - install: npm install screwdriver-template-main
#            - validate: ./node_modules/.bin/template-validate
#            - publish: ./node_modules/.bin/template-publish
#    tag:
#        steps:
#            - install: npm install screwdriver-template-main
#            - token: echo $SD_TOKEN
#            - tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag latest
#    use-tag:
#        template: tifftemplate@latest
---
jobs:
    main:
        description: 'hello I am the first job that will run test some things'
        requires: [~pr, ~commit]
        image: node:14
        steps:
            - meta: meta get event.creator
    
