#pipeline 6
shared:
    image: node:8
    steps:
        - echo: echo hi
jobs:
    main:
        description: 'hello I am the first job that will run'
        requires: [~pr, ~commit]
        steps:
            - echo: |
                cat $SD_SOURCE_DIR/ascii-art.txt
            - set-coverage-and-test-results: |
                meta set tests.coverage 40.023423 # this should be the coverage percentage number
                meta set tests.results 4/10 # this should be `pass_tests_number/total_tests_number`
    internal_fork1:
        requires: [main]
    internal_fork2:
        requires: [main]
    internal_fork3:
        requires: [main]
    internal_fork4:
        requires: [main]
    join_job:
        description: 'job to test the specific branch requires feature'
        requires: ['internal_fork1', 'internal_fork2', 'internal_fork3', 'internal_fork4']
        steps:
            - echo: echo hi
            - set-coverage-and-test-results: |
                meta set tests.coverage 33.3 # this should be the coverage percentage number
                meta set tests.results 4/10 # this should be `pass_tests_number/total_tests_number`
